env:
  TERM: xterm-256color

font:
  normal:
    family: Inconsolata
    style: Regular
  italic:
    family: Inconsolata
    style: Italic
  bold:
    family: Inconsolata
    style: Bold
  bold_italic:
    family: Inconsolata
    style: Bold Italic
  size: 12
  use_thin_strokes: false

scrolling:
  history: 10000

window:
  decorations: none
  startup_mode: Maximized
  padding:
    x: 5
    y: 5

mouse:
  hide_when_typing: true

key_bindings:
  - { key: W,       mods: Super,              chars:  "w"                 }
  - { key: M,       mods: Super,              chars:  "m"                 }
  - { key: S,       mods: Super,              chars:  "\x13"              }
  - { key: Key1,    mods: Super,              chars:  "\x131"             }
  - { key: Key2,    mods: Super,              chars:  "\x132"             }
  - { key: Key3,    mods: Super,              chars:  "\x133"             }
  - { key: Key4,    mods: Super,              chars:  "\x134"             }
  - { key: Key5,    mods: Super,              chars:  "\x135"             }
  - { key: Key6,    mods: Super,              chars:  "\x136"             }
  - { key: Key7,    mods: Super,              chars:  "\x137"             }
  - { key: Key8,    mods: Super,              chars:  "\x138"             }
  - { key: Key9,    mods: Super,              chars:  "\x139"             }
  - { key: H,       mods: Super,              chars:  "\x13h"             }
  - { key: J,       mods: Super,              chars:  "\x13j"             }
  - { key: K,       mods: Super,              chars:  "\x13k"             }
  - { key: L,       mods: Super,              chars:  "\x13l"             }

# GRUVBOX BABY
colors:
  primary:
    background: '#1d2021' # hard contrast
    # background: '#282828' # normal contrast
    # background: '#32302f' # soft contrast
    foreground: '#ebdbb2'

  # Normal colors
  normal:
    black:   '#282828'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'

  # Bright colors
  bright:
    black:   '#928374'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'
