env:
  TERM: xterm-256color

font:
  normal:
    family: Meslo LGS NF
    style: Regular
  italic:
    family: Meslo LGS NF
    style: Italic
  bold:
    family: Meslo LGS NF
    style: Bold
  bold_italic:
    family: Meslo LGS NF
    style: Bold Italic
  size: 14
  use_thin_strokes: false
  glyph_offset:
    x: 0
    y: 1

scrolling:
  history: 10000

window:
  decorations: none
  startup_mode: Maximized

mouse:
  hide_when_typing: true

key_bindings:
  - { key: Return,  mods: Command|Alt|Control,  action: SpawnNewInstance    } 
  - { key: Space,   mods: Command,              chars:  "\x00"              }

# GRUVBOX BABY
colors:
  primary:
    background: '#1d2021' # hard contrast
    # background: '#282828' # normal contrast
    # background: '#32302f' # soft contrast
    foreground: '#ebdbb2'

  # Normal colors
  normal:
    black:   '#282828'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'

  # Bright colors
  bright:
    black:   '#928374'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'
