env:
  TERM: xterm-256color

font:
  normal:
    family: MesloLGS NF
    style: Regular
  italic:
    family: MesloLGS NF
    style: Italic
  bold:
    family: MesloLGS NF
    style: Bold
  bold_italic:
    family: MesloLGS NF
    style: Bold Italic
  size: 10
  use_thin_strokes: false

window:
  decorations: none
  startup_mode: Windowed
  padding:
    x: 5
    y: 5
  title: 'vimwiki alacritty'

mouse:
  hide_when_typing: true

shell:
  program: /bin/zsh
  args:
    - -c
    - '/usr/local/bin/nvim -u "~/vimwiki/scripts/init.vim" -c "VimwikiIndex"'

key_bindings:
  - { key: W, mods: Command, chars:  "w" }
  - { key: M, mods: Command, chars:  "m" }

# GRUVBOX (LIGHT) BABY
colors:
  # Default colors
  primary:
    # background: '#f9f5d7' # hard contrast
    # background: '#fbf1c7' # normal contrast
    background: '#f2e5bc' # soft contrast
    foreground: '#3c3836'

  # Normal colors
  normal:
    black:   '#fbf1c7'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#7c6f64'

  # Bright colors
  bright:
    black:   '#928374'
    red:     '#9d0006'
    green:   '#79740e'
    yellow:  '#b57614'
    blue:    '#076678'
    magenta: '#8f3f71'
    cyan:    '#427b58'
    white:   '#3c3836'

