# shellcheck shell=bash

shopt -s autocd
shopt -s cdspell
shopt -s dirspell

# standard variables
source ~/.variables

# standard aliases
source ~/.aliases

# ssh aliases (not in the git repo for obvious reasons)
[ -f ~/.ssh_aliases ] && source ~/.ssh_aliases

# local config
source ~/.bashrc-local

# load theme
eval "$(starship init bash)"

clear
