# shellcheck shell=bash

autoload -Uz compinit; compinit
bindkey -e
setopt AUTO_CD

# standard variables
source ~/.variables

# standard aliases
source ~/.aliases

# ssh aliases (not in the git repo for obvious reasons)
[ -f ~/.ssh_aliases ] && source ~/.ssh_aliases

# local config
source ~/.zshrc-local

# load theme
eval "$(starship init zsh)"

clear
