# shellcheck shell=bash

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export EDITOR=/usr/local/bin/nvim
export STARSHIP_CONFIG=~/.starship
export HOMEBREW_NO_ANALYTICS=1
export FZF_DEFAULT_COMMAND='fd'

# basic aliases
alias f='open -a Finder ./' # opens cd in finder
alias c='clear'
alias fuck="sudo !!"
alias ls='ls -Gh'
alias ll='ls -Glh'
alias lt='ls -GlAtrh'
alias l='ls -GlAh'
alias lpo='gstat --printf="%A %a %n\n" *'
alias hideDesktop='defaults write com.apple.finder CreateDesktop false; killall Finder'
alias showDesktop='defaults write com.apple.finder CreateDesktop true; killall Finder'

# yabai
alias yabai-restart='launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"'

# docker
alias dockstat='docker stats --format "table {{.Container}}\t{{.Name}}\t{{.CPUPerc}}\t{{.MemUsage}}\t{{.PIDs}}"'

# editors
alias code='code -r'
alias fcode='fzf | xargs -I{} code -r {}'
alias vim='nvim'

# rust
alias cgb='cargo build'
alias cgr='cargo run -q'

# cmake
alias cmconf='cmake -Bbuild -H. -GNinja'
alias cmbuild='ninja -Cbuild'

# lazygit
alias lg='lazygit'

# load nvm (not done by default cause it's slow)
nvm_init() {
    export NVM_DIR="$HOME/.nvm"
    # shellcheck source=/dev/null
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    # shellcheck source=/dev/null
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
}

# load pyenv and pyenv-virtualenv (also slow)
pyenv_init() {
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
}

# captures output of a PID
capture() {
    sudo dtrace -p "$1" -qn '
        syscall::write*:entry
        /pid == $target && arg0 == 1/ {
            printf("%s", copyinstr(arg1, arg2));
        }
    '
}

# load localized profile
# shellcheck disable=1090
# source "$HOME/.dotfiles/$(whoami)@$(hostname)/.zprofile"

# load theme
eval "$(starship init zsh)"

clear
