# shellcheck shell=bash

source ~/.bashrc

export STARSHIP_CONFIG=~/.starship

# vscode for interactive rebase
#export EDITOR='code -r'
export EDITOR='nvim'

# bash history persistence
export PROMPT_COMMAND='history -a' export HISTFILE=/root/.bash_history

# starship
eval "$(starship init bash)"
