# shellcheck shell=bash

set -o vi
bind ^l:clear-screen
shopt -s autocd

# standard variables
source ~/.variables

# standard aliases
source ~/.aliases

# ssh aliases (not in the git repo for obvious reasons)
[ -f ~/.ssh-aliases ] && source ~/.ssh-aliases

# local config
[ -f ~/.bashrc-local ] && source ~/.bashrc-local

# load theme
eval "$(starship init bash)"

clear
