# shellcheck shell=bash

shopt -s autocd
shopt -s cdspell
shopt -s dirspell

# standard variables
source ~/.variables

# standard aliases
source ~/.aliases

# ssh aliases (not in the git repo for obvious reasons)
[ -f ~/.ssh-aliases ] && source ~/.ssh-aliases

# local config
[ -f ~/.bashrc-local ] && source ~/.bashrc-local

# load theme
eval "$(starship init bash)"

clear
