# vim: syntax=zsh

autoload -Uz compinit; compinit
bindkey -e
disable r
setopt AUTO_CD

# standard variables
source ~/.variables

# standard aliases
source ~/.aliases

# ssh aliases (not in the git repo for obvious reasons)
[ -f ~/.ssh-aliases ] && source ~/.ssh-aliases

# local config
[ -f ~/.zshrc-local ] && source ~/.zshrc-local

# load theme
eval "$(starship init zsh)"

# reload aliases
alias ref='source ~/.zshrc && echo reloaded shell'
alias href='exec $SHELL'

clear

PATH="/Volumes/FilesHDD/ethanbailey/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/Volumes/FilesHDD/ethanbailey/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/Volumes/FilesHDD/ethanbailey/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/Volumes/FilesHDD/ethanbailey/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/Volumes/FilesHDD/ethanbailey/perl5"; export PERL_MM_OPT;
